/**
 * Action Executor Service for DoctorSathi Semi-Automation
 * Executes validated actions generated by AI
 */

import dbService from './db.service.js';
import logger from '../utils/logger.js';
import { ACTION_TYPES } from '../types/actions.js';

class ActionExecutorService {
    /**
     * Execute prescription creation
     * @param {object} data - Prescription data
     * @param {string} doctorId - Doctor ID
     * @returns {Promise<object>} Execution result
     */
    async executePrescription(data, doctorId) {
        try {
            logger.info('Executing prescription creation', { patientId: data.patientId, medication: data.medication });

            // Validate patient exists
            const patient = await dbService.prisma.patientWalletMapping.findUnique({
                where: { id: data.patientId },
            });

            if (!patient) {
                throw new Error('Patient not found');
            }

            // Generate prescription ID
            const prescriptionId = `RX-${Date.now()}`;

            // Create prescription
            const prescription = await dbService.prisma.prescription.create({
                data: {
                    prescriptionId,
                    patientId: data.patientId,
                    doctorId,
                    medication: data.medication,
                    dosage: data.dosage,
                    instructions: data.instructions,
                    expiryDate: data.expiryDate ? new Date(data.expiryDate) : null,
                    status: 'ACTIVE',
                },
            });

            logger.info('Prescription created successfully', { prescriptionId });

            return {
                success: true,
                message: `Prescription created successfully`,
                data: {
                    prescriptionId: prescription.prescriptionId,
                    id: prescription.id,
                },
            };
        } catch (error) {
            logger.error('Error executing prescription creation:', error);
            return {
                success: false,
                message: error.message || 'Failed to create prescription',
            };
        }
    }

    /**
     * Execute appointment scheduling
     * @param {object} data - Appointment data
     * @param {string} doctorId - Doctor ID
     * @returns {Promise<object>} Execution result
     */
    async executeAppointment(data, doctorId) {
        try {
            logger.info('Executing appointment creation', { patientId: data.patientId, scheduledAt: data.scheduledAt });

            // Validate patient exists
            const patient = await dbService.prisma.patientWalletMapping.findUnique({
                where: { id: data.patientId },
            });

            if (!patient) {
                throw new Error('Patient not found');
            }

            // Generate appointment ID
            const appointmentId = `APT-${Date.now()}`;

            // Create appointment
            const appointment = await dbService.prisma.appointment.create({
                data: {
                    appointmentId,
                    patientId: data.patientId,
                    doctorId,
                    title: data.title,
                    description: data.description || '',
                    scheduledAt: new Date(data.scheduledAt),
                    status: 'SCHEDULED',
                    location: data.location || 'Clinic',
                    notes: data.notes || '',
                },
            });

            logger.info('Appointment created successfully', { appointmentId });

            return {
                success: true,
                message: `Appointment scheduled successfully`,
                data: {
                    appointmentId: appointment.appointmentId,
                    id: appointment.id,
                    scheduledAt: appointment.scheduledAt.toISOString(),
                },
            };
        } catch (error) {
            logger.error('Error executing appointment creation:', error);
            return {
                success: false,
                message: error.message || 'Failed to schedule appointment',
            };
        }
    }

    /**
     * Execute lab test order
     * @param {object} data - Lab test data
     * @param {string} doctorId - Doctor ID
     * @returns {Promise<object>} Execution result
     */
    async executeLabTest(data, doctorId) {
        try {
            logger.info('Executing lab test order', { patientId: data.patientId, testName: data.testName });

            // Validate patient exists
            const patient = await dbService.prisma.patientWalletMapping.findUnique({
                where: { id: data.patientId },
            });

            if (!patient) {
                throw new Error('Patient not found');
            }

            // Generate test ID
            const testId = `LAB-${Date.now()}`;

            // Create lab test
            const labTest = await dbService.prisma.labTest.create({
                data: {
                    testId,
                    patientId: data.patientId,
                    doctorId,
                    testName: data.testName,
                    testType: data.testType,
                    status: 'PENDING',
                    results: null,
                    performedAt: null,
                },
            });

            logger.info('Lab test ordered successfully', { testId });

            return {
                success: true,
                message: `Lab test ordered successfully`,
                data: {
                    testId: labTest.testId,
                    id: labTest.id,
                },
            };
        } catch (error) {
            logger.error('Error executing lab test order:', error);
            return {
                success: false,
                message: error.message || 'Failed to order lab test',
            };
        }
    }

    /**
     * Execute medical record update
     * @param {object} data - Medical record data
     * @param {string} doctorId - Doctor ID
     * @returns {Promise<object>} Execution result
     */
    async executeRecord(data, doctorId) {
        try {
            logger.info('Executing medical record creation', { patientId: data.patientId, title: data.title });

            // Validate patient exists
            const patient = await dbService.prisma.patientWalletMapping.findUnique({
                where: { id: data.patientId },
            });

            if (!patient) {
                throw new Error('Patient not found');
            }

            // Generate record ID
            const recordId = `REC-${Date.now()}`;

            // Create medical record
            const record = await dbService.prisma.medicalRecord.create({
                data: {
                    recordId,
                    patientId: data.patientId,
                    doctorId,
                    title: data.title,
                    description: data.description,
                    recordType: data.recordType || 'GENERAL',
                    ipfsHash: data.ipfsHash || '',
                    fileName: data.fileName || '',
                },
            });

            logger.info('Medical record created successfully', { recordId });

            return {
                success: true,
                message: `Medical record created successfully`,
                data: {
                    recordId: record.recordId,
                    id: record.id,
                },
            };
        } catch (error) {
            logger.error('Error executing medical record creation:', error);
            return {
                success: false,
                message: error.message || 'Failed to create medical record',
            };
        }
    }

    /**
     * Execute action based on type
     * @param {object} action - Action object
     * @param {string} doctorId - Doctor ID
     * @returns {Promise<object>} Execution result
     */
    async executeAction(action, doctorId) {
        switch (action.type) {
            case ACTION_TYPES.CREATE_PRESCRIPTION:
                return this.executePrescription(action.data, doctorId);

            case ACTION_TYPES.SCHEDULE_APPOINTMENT:
                return this.executeAppointment(action.data, doctorId);

            case ACTION_TYPES.ORDER_LAB_TEST:
                return this.executeLabTest(action.data, doctorId);

            case ACTION_TYPES.UPDATE_MEDICAL_RECORD:
                return this.executeRecord(action.data, doctorId);

            default:
                return {
                    success: false,
                    message: `Unknown action type: ${action.type}`,
                };
        }
    }
}

export default new ActionExecutorService();
