/**
 * Action Types and Schemas for DoctorSathi Semi-Automation
 * Defines the structure of executable actions generated by AI
 */

// Action type constants
export const ACTION_TYPES = {
    CREATE_PRESCRIPTION: 'CREATE_PRESCRIPTION',
    SCHEDULE_APPOINTMENT: 'SCHEDULE_APPOINTMENT',
    ORDER_LAB_TEST: 'ORDER_LAB_TEST',
    UPDATE_MEDICAL_RECORD: 'UPDATE_MEDICAL_RECORD',
    SEND_NOTIFICATION: 'SEND_NOTIFICATION',
};

// Action status constants
export const ACTION_STATUS = {
    PENDING: 'pending',
    EXECUTING: 'executing',
    EXECUTED: 'executed',
    FAILED: 'failed',
};

// Action priority levels
export const ACTION_PRIORITY = {
    LOW: 'low',
    MEDIUM: 'medium',
    HIGH: 'high',
    URGENT: 'urgent',
};

/**
 * Validate action data based on type
 * @param {string} type - Action type
 * @param {object} data - Action data
 * @returns {object} Validation result
 */
export function validateActionData(type, data) {
    const errors = [];

    switch (type) {
        case ACTION_TYPES.CREATE_PRESCRIPTION:
            if (!data.patientId) errors.push('Patient ID is required');
            if (!data.medication) errors.push('Medication is required');
            if (!data.dosage) errors.push('Dosage is required');
            if (!data.instructions) errors.push('Instructions are required');
            break;

        case ACTION_TYPES.SCHEDULE_APPOINTMENT:
            if (!data.patientId) errors.push('Patient ID is required');
            if (!data.scheduledAt) errors.push('Appointment date/time is required');
            if (!data.title) errors.push('Appointment title is required');
            break;

        case ACTION_TYPES.ORDER_LAB_TEST:
            if (!data.patientId) errors.push('Patient ID is required');
            if (!data.testName) errors.push('Test name is required');
            if (!data.testType) errors.push('Test type is required');
            break;

        case ACTION_TYPES.UPDATE_MEDICAL_RECORD:
            if (!data.patientId) errors.push('Patient ID is required');
            if (!data.title) errors.push('Record title is required');
            if (!data.description) errors.push('Record description is required');
            break;

        default:
            errors.push('Unknown action type');
    }

    return {
        valid: errors.length === 0,
        errors,
    };
}

/**
 * Create action object
 * @param {string} type - Action type
 * @param {object} data - Action data
 * @param {string} description - Human-readable description
 * @param {string} priority - Action priority
 * @returns {object} Action object
 */
export function createAction(type, data, description, priority = ACTION_PRIORITY.MEDIUM) {
    return {
        id: `action-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
        type,
        status: ACTION_STATUS.PENDING,
        data,
        description,
        priority,
        createdAt: new Date().toISOString(),
    };
}
